spring:
  profiles:
    active: dev
  #时间格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
server:
  context-path: /task

#swagger:
#  docket:
#    user:
#      title: group-a
#      version: 1.0.0-SNAPSHOT
#      base-package: com.sunny.task.user
#      exclude-path: /error
#      contact:
#          email: 2385585770@qq.com
#          url: http://spring4all.com
#      termsOfServiceUrl: https://gitee.com/didispace/spring-boot-starter-swagger






